# AtCoderのユーザ名、提出履歴を管理するために使うリモートリポジトリのクローンURLを設定します。

'atcoder_username' = 'tawainfer'
'clone_url' = 'git@github.com:tawainfer/test-repo-for-atscm.git'



# 問題を分類するための分類名とキーワードを設定します。
# ソースファイルを配置する際、設定した分類名で親ディレクトリが作成されます。
# キーワードを設定すると、その分類にはproblem_idがマッチしている問題のみ適応されます。
# 問題のproblem_idはAtCoderの提出ページのURL、AtCoder Problems APIから確認してください。

[classification]
'abc' = ['abc']
'arc' = ['arc']
'agc' = ['agc']


# 日本語が使えます。シングルクォーテーションで囲んでください。

# '競プロ典型90問' = ['typical90']
# '競技プログラミングの鉄則' = ['tessoku_book']


# 正規表現も使えます。シングルクォーテーションで囲むとエスケープが不要になり楽です。

# 'abc-a' = ['^abc[0-9]{3}_a$']


# キーワードは複数書くことができます。
# 以下は「Socks」シリーズの問題を集める例です。

# 'socks' = ['abc295_c', 'abc334_c', 'abc352_g']


# どの分類のキーワードにもマッチしない問題の場合、atscmでは管理されません。
# 以下のようなキーワードの書き方をすることで、全ての問題を管理するディレクトリを作ることが出来ます。

# 'all' = ['']


